name: UIpath Primary
# Controls when the action will run. 
on:
  pull_request:
    branches:
      - development
    paths:
      - dev/primary/**
      
  workflow_dispatch:
      
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
#       - name: Get vault secrets
#         id: secrets
#         uses: hashicorp/vault-action@v2.3.0
#         with:
#           url: https://vault.tools.dcsg.com
#           method: approle
#           roleId: ${{ secrets.VAULT_ROLE_ID_DEV }}
#           secretId: ${{ secrets.VAULT_SECRET_ID_DEV }}
#           secrets: |
#             concourse/integration/uipath/azure/nonprodjson AZURE_CREDENTIALS | AZURE_CREDENTIALS_PRI 
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Detach uipathapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-NP \
            -n uipathapp \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Detach orch77385is
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-NP \
            -n orch77385is \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Detach orch6051cwh
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-NP \
            -n orch6051cwh \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name uipathprimary \
            --resource-group ES-RPA-NP \
            --template-file armtemplates/uipath.json \
            --parameters '@dev/primary/azuredeploy.parameters.json'
