# This is a basic workflow to help you get started with Actions
name: UIpath Disaster Recovery PROD
# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["UIpath Machines and Robots  primary PROD"]
    types:
      - completed
      
  workflow_dispatch:
      
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
#       - name: Get vault secrets
#         id: secrets
#         uses: hashicorp/vault-action@v2.3.0
#         with:
#           url: https://vault.tools.dcsg.com
#           method: approle
#           roleId: ${{ secrets.VAULT_ROLE_ID }}
#           secretId: ${{ secrets.VAULT_SECRET_ID }}
#           secrets: |
#             concourse/integration/uipath/azure/prodjson-dr AZURE_CREDENTIALS_DR | AZURE_CREDENTIALS_DR_PRD 
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD_DR }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Detach uipathappproddr
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-PROD-DR \
            -n uipathappproddr \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Detach orch624b2isprod
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-PROD-DR \
            -n orch624b2isprod \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Detach orch10066whprod
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp vnet-integration remove \
            -g ES-RPA-PROD-DR \
            -n orch10066whprod \
            --subscription e5379bc3-8dfe-45a9-9b16-0044fd8f5761
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name uipathdr \
            --resource-group ES-RPA-PROD-DR \
            --template-file armtemplates/uipathdr.json \
            --parameters '@prod/secondary/azuredeploy.parameters.json' --verbose
